/* 日日有益前端：原生 DOM 实现估算确认、设置和周月存档。 */
(function () {
  "use strict";
  var API = "./api";
  var state = { date: localDate(), entries: [], summary: {}, profile: {}, preferences: {}, estimate: null, period: 7 };
  var $ = function (id) { return document.getElementById(id); };
  var txt = function (node, value) { if (node) node.textContent = value == null ? "" : String(value); };
  var val = function (id) { var node = $(id); return node ? node.value.trim() : ""; };
  var num = function (id) { var raw = val(id); return raw === "" ? null : Number(raw); };
  function localDate() { var d = new Date(); return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0"); }
  function api(method, path, body, options) { options = options || { headers: { Accept: "application/json" } }; options.method = method; if (body !== undefined) { options.headers = options.headers || {}; options.headers["Content-Type"] = "application/json"; options.body = JSON.stringify(body); } return fetch(API + path, options).then(function (response) { return response.json().catch(function () { return {}; }).then(function (payload) { if (!response.ok || payload.ok === false) { throw new Error(payload.error && payload.error.message || "请求没有完成"); } return payload.data === undefined ? payload : payload.data; }); }); }
  function setMessage(message, error) { txt($("global-message"), message || ""); $("global-message").className = error ? "message error" : "message"; }
  function display(value) { return Number.isFinite(Number(value)) ? String(Math.round(Number(value) * 10) / 10) : "未记录"; }
  function kind(entry) { return entry.type || "meal"; }
  function mealCalories(entry) { return Number(entry.calories || 0); }
  function exerciseCalories(entry) { return entry.calories_burned != null ? Number(entry.calories_burned) : null; }
  function loadAll() { setMessage("正在读取今天的数据…"); return Promise.all([api("GET", "/profile"), api("GET", "/preferences"), api("GET", "/days/" + state.date + "/entries"), api("GET", "/days/" + state.date + "/summary")]).then(function (all) { state.profile = all[0] || {}; state.preferences = all[1] || {}; state.entries = Array.isArray(all[2].entries) ? all[2].entries : []; state.summary = all[3] || {}; renderProfile(); renderPreferences(); renderEntries(); renderSummary(); setMessage(""); return loadArchive(); }).catch(function (error) { setMessage(error.message || "暂时无法读取数据，请稍后再试。", true); renderEntries(); }); }
  function renderSummary() { var data = state.summary, intake = data.calories_in, exercise = data.exercise_kcal, weight = data.weight_kg, target = data.calorie_target, remaining = target == null || intake == null ? null : Number(target) - Number(intake); txt($("summary-calories-label"), intake == null ? "未记录" : display(intake) + " 千卡"); txt($("summary-exercise"), exercise == null ? "未记录" : display(exercise)); txt($("summary-weight"), weight == null ? "未记录" : display(weight)); txt($("summary-remaining"), remaining == null ? "未记录" : display(remaining)); txt($("summary-calories-note"), target == null ? "填写档案后会显示每日预算。" : "每日预算约 " + display(target) + " 千卡（估算）"); $("calorie-progress").style.width = target && intake != null ? Math.max(0, Math.min(100, intake / target * 100)) + "%" : "0%"; }
  function renderEntries() { var box = $("entries-list"); box.textContent = ""; txt($("entry-count"), state.entries.length ? state.entries.length + " 条" : ""); if (!state.entries.length) { var empty = document.createElement("p"); empty.className = "empty muted"; txt(empty, "今天还没有记录，先从一件小事开始吧。"); box.appendChild(empty); return; } state.entries.forEach(function (entry) { var row = document.createElement("div"); row.className = "entry"; var details = document.createElement("div"); var title = document.createElement("div"); title.className = "entry-title"; txt(title, kind(entry) === "exercise" ? "运动" : kind(entry) === "weight" ? "体重" : (entry.meal_type || "饮食")); var meta = document.createElement("div"); meta.className = "entry-meta"; var description = kind(entry) === "weight" ? display(entry.weight_kg) + " 公斤" : entry.name || "手动记录"; txt(meta, description); details.appendChild(title); details.appendChild(meta); var right = document.createElement("div"); right.className = "entry-value"; txt(right, kind(entry) === "exercise" ? (exerciseCalories(entry) == null ? "未填写消耗" : display(exerciseCalories(entry)) + " 千卡") : kind(entry) === "weight" ? "" : (mealCalories(entry) ? display(mealCalories(entry)) + " 千卡" : "未填写热量")); var remove = document.createElement("button"); remove.type = "button"; remove.className = "delete-entry"; txt(remove, "删除"); var id = entry.id; remove.addEventListener("click", function () { api("DELETE", "/days/" + state.date + "/entries/" + encodeURIComponent(id)).then(loadAll); }); right.appendChild(remove); row.appendChild(details); row.appendChild(right); box.appendChild(row); }); }
  function renderProfile() { var p = state.profile.profile || state.profile; [["birth-year", "birth_year"], ["height", "height_cm"], ["profile-weight", "weight_kg"], ["target-weight", "target_weight_kg"], ["deficit-kcal", "deficit_kcal"]].forEach(function (pair) { if (p[pair[1]] != null) $(pair[0]).value = p[pair[1]]; }); if (p.sex) $("profile-sex").value = p.sex; if (p.activity_level) $("activity").value = p.activity_level; }
  function renderPreferences() { var p = state.preferences.preferences || state.preferences, items = p.items && p.items.general || {}; ["avoid", "reluctant", "neutral", "love"].forEach(function (level) { $("pref-" + level).value = Object.keys(items).filter(function (name) { return items[name] === level; }).join("、"); }); }
  function toggleFields() { var type = val("entry-type"); $("meal-fields").hidden = type !== "meal"; $("exercise-fields").hidden = type !== "exercise"; $("weight-fields").hidden = type !== "weight"; }
  function submitEntry(event) { event.preventDefault(); var type = val("entry-type"), body = { type: type, source: "manual" }; if (type === "meal") { body.name = val("meal-text"); body.meal_type = val("meal-kind"); body.calories = num("meal-calories"); } else if (type === "exercise") { body.name = val("exercise-text"); body.calories_burned = num("exercise-calories"); } else body.weight_kg = num("weight-value"); if ((!body.name && type !== "weight") || (type === "weight" && !(body.weight_kg > 0))) { txt($("entry-error"), "请填写有效内容。"); return; } api("POST", "/days/" + state.date + "/entries", body).then(function () { $("entry-form").reset(); toggleFields(); return loadAll(); }).catch(function (error) { txt($("entry-error"), error.message); }); }
  function split(id) { return val(id).split(/[，,、\n]/).map(function (x) { return x.trim(); }).filter(Boolean); }
  function submitProfile(event) { event.preventDefault(); var body = { birth_year: num("birth-year"), height_cm: num("height"), weight_kg: num("profile-weight"), target_weight_kg: num("target-weight"), activity_level: val("activity") }, sex = val("profile-sex"), deficit = num("deficit-kcal"); if (sex) body.sex = sex; if (deficit != null) body.deficit_kcal = deficit; api("PUT", "/profile", body).then(loadAll).catch(function (error) { txt($("profile-error"), error.message); }); }
  function submitPreferences(event) { event.preventDefault(); var items = {}; ["avoid", "reluctant", "neutral", "love"].forEach(function (level) { split("pref-" + level).forEach(function (name) { items[name] = level; }); }); api("PUT", "/preferences", { items: { general: items } }).then(loadAll).catch(function (error) { txt($("preferences-error"), error.message); }); }
  function renderEstimate() { var box = $("estimate-items"); box.textContent = ""; (state.estimate.items || []).forEach(function (item, index) { var row = document.createElement("div"); row.className = "estimate-item"; var name = document.createElement("input"); name.value = item.name || "食物"; name.dataset.index = index; name.className = "estimate-name"; name.setAttribute("aria-label", "食物名称"); var portion = document.createElement("input"); portion.value = item.portion || ""; portion.placeholder = "份量"; portion.className = "estimate-portion"; portion.setAttribute("aria-label", "份量"); var kcal = document.createElement("input"); kcal.type = "number"; kcal.value = item.kcal_best == null ? "" : item.kcal_best; kcal.className = "estimate-kcal"; kcal.setAttribute("aria-label", "确认热量"); var remove = document.createElement("button"); remove.type = "button"; txt(remove, "删除"); remove.addEventListener("click", function () { state.estimate.items.splice(index, 1); renderEstimate(); }); var details = document.createElement("small"); details.className = "estimate-meta"; txt(details, "估算区间 " + display(item.kcal_low) + "–" + display(item.kcal_high) + " 千卡 · 蛋白 " + display(item.protein_g) + "g · 碳水 " + display(item.carbs_g) + "g · 脂肪 " + display(item.fat_g) + "g"); row.appendChild(name); row.appendChild(portion); row.appendChild(kcal); row.appendChild(remove); row.appendChild(details); box.appendChild(row); }); txt($("estimate-questions"), (state.estimate.questions || []).join("；")); $("estimate-result").hidden = false; }
  function submitEstimate(event) { event.preventDefault(); var text = val("estimate-text"), file = $("estimate-photo").files[0], data = new FormData(); if (text) data.append("text", text); if (file) data.append("image", file, file.name); $("estimate-button").disabled = true; txt($("estimate-status"), "识别中…"); txt($("estimate-error"), ""); fetch(API + "/estimate", { method: "POST", headers: { Accept: "application/json" }, body: data }).then(function (response) { return response.json().then(function (payload) { if (!response.ok || payload.ok === false) throw new Error(payload.error && payload.error.message || "估算失败"); return payload.data; }); }).then(function (data) { state.estimate = data; renderEstimate(); txt($("estimate-status"), data.error ? "估算失败，可手动添加" : "请确认"); if (data.error) txt($("estimate-error"), data.error); }).catch(function (error) { state.estimate = { items: [], questions: [], error: error.message }; renderEstimate(); txt($("estimate-error"), error.message || "估算失败，可直接手动记录。"); txt($("estimate-status"), "估算失败，可手动添加"); }).finally(function () { $("estimate-button").disabled = false; }); }
  function addEstimateItem() { var name = val("estimate-add-name"); if (!name) return; state.estimate = state.estimate || { items: [], questions: [] }; state.estimate.items.push({ name: name, portion: "", kcal_best: 0 }); $("estimate-add-name").value = ""; renderEstimate(); }
  function saveEstimate() { if (!state.estimate) return; var items = Array.prototype.map.call(document.querySelectorAll(".estimate-item"), function (row, index) { var original = state.estimate.items[index] || {}; return { type: "meal", name: row.querySelector(".estimate-name").value.trim(), portion: row.querySelector(".estimate-portion").value.trim(), unit: original.unit || "份", calories: Number(row.querySelector(".estimate-kcal").value || 0), kcal_low: original.kcal_low == null ? 0 : original.kcal_low, kcal_high: original.kcal_high == null ? Number(row.querySelector(".estimate-kcal").value || 0) : original.kcal_high, kcal_best: Number(row.querySelector(".estimate-kcal").value || 0), protein_g: original.protein_g || 0, carbs_g: original.carbs_g || 0, fat_g: original.fat_g || 0, confidence: original.confidence == null ? 0 : original.confidence, note: original.note || "", source: state.estimate.source || "text", provider: state.estimate.provider, model: state.estimate.model, estimate: state.estimate }; }).filter(function (item) { return item.name; }); api("POST", "/days/" + state.date + "/entries", { entries: items, source: state.estimate.source || "text", estimate: state.estimate }).then(function () { $("estimate-result").hidden = true; state.estimate = null; setMessage("已确认并记账"); return loadAll(); }).catch(function (error) { txt($("estimate-error"), error.message); }); }
  function renderArchive(data) { var box = $("archive-result"); box.textContent = ""; var totals = data.totals || {}, averages = data.averages || {}, days = data.days || []; var table = document.createElement("table"); table.className = "archive-table"; var header = document.createElement("tr"); ["日期", "摄入", "运动", "体重", "趋势"].forEach(function (title, index) { var cell = document.createElement("th"); if (index === 4) cell.className = "archive-bar-cell"; txt(cell, title); header.appendChild(cell); }); table.appendChild(header); var maximum = Math.max.apply(null, days.map(function (day) { return Number(day.calories_in) || 0; }).concat([1])); days.forEach(function (day) { var row = document.createElement("tr"); [day.date, display(day.calories_in), display(day.calories_out), day.weight_kg == null ? "—" : display(day.weight_kg)].forEach(function (value) { var cell = document.createElement("td"); txt(cell, value); row.appendChild(cell); }); var barCell = document.createElement("td"); barCell.className = "archive-bar-cell"; var bar = document.createElement("i"); bar.className = "archive-bar"; bar.style.width = Math.max(2, Number(day.calories_in || 0) / maximum * 100) + "%"; barCell.appendChild(bar); row.appendChild(barCell); table.appendChild(row); }); box.appendChild(table); var note = document.createElement("p"); note.className = "muted"; txt(note, "合计摄入 " + display(totals.calories_in) + " 千卡 · 日均 " + display(averages.calories_in) + " 千卡"); box.appendChild(note); }
  function loadArchive() { var end = state.date, start = new Date(end + "T00:00:00"); start.setDate(start.getDate() - state.period + 1); function iso(d) { return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0"); } return api("GET", "/range?from=" + iso(start) + "&to=" + end).then(renderArchive).catch(function () { txt($("archive-result"), "存档暂时不可用"); }); }
  function renderPlan(data) { var box = $("plan-result"); box.textContent = ""; box.hidden = false; (data.meals || []).forEach(function (meal) { var item = document.createElement("article"); item.className = "meal-plan"; var title = document.createElement("h3"); txt(title, meal.meal || "一餐"); var desc = document.createElement("p"); txt(desc, (meal.name || "按偏好搭配") + (meal.calories_kcal == null ? "" : " · 约 " + display(meal.calories_kcal) + " 千卡")); item.appendChild(title); item.appendChild(desc); box.appendChild(item); }); }
  function makePlan() { txt($("plan-status"), "生成中…"); $("plan-button").disabled = true; api("POST", "/days/" + state.date + "/plan", {}).then(function (data) { renderPlan(data); txt($("plan-status"), "已生成"); }).catch(function (error) { txt($("plan-error"), error.message); }).finally(function () { $("plan-button").disabled = false; }); }
  function providerFields() { var box = $("provider-settings"); box.textContent = ""; var provider = val("settings-provider"), config = state.settings && state.settings.providers && state.settings.providers[provider] || {}; [["model", "模型"], ["timeout_s", "超时（秒）"], ["base_url", "服务地址"]].forEach(function (pair) { if (provider === "openai_compatible" || pair[0] !== "base_url") { var label = document.createElement("label"); var input = document.createElement("input"); input.id = "settings-" + pair[0]; input.type = pair[0] === "timeout_s" ? "number" : "text"; if (pair[0] === "timeout_s") { input.min = "1"; input.max = "600"; } input.value = config[pair[0]] == null ? "" : config[pair[0]]; label.htmlFor = input.id; txt(label, pair[1]); box.appendChild(label); box.appendChild(input); } }); if (provider === "openai_compatible") { var keyLabel = document.createElement("label"); var key = document.createElement("input"); key.type = "password"; key.id = "settings-api-key"; key.placeholder = config.has_api_key ? "已保存，留空保持不变" : "未设置"; keyLabel.htmlFor = key.id; txt(keyLabel, "API 密钥（留空保持不变）"); box.appendChild(keyLabel); box.appendChild(key); } }
  function loadSettings() { return api("GET", "/settings").then(function (data) { state.settings = data; $("settings-provider").value = data.provider || "mock"; $("settings-retain-photos").checked = Boolean(data.retain_photos); providerFields(); var config = data.providers && data.providers[data.provider] || {}; Object.keys(config).forEach(function (key) { var input = $("settings-" + key); if (input) input.value = config[key] || ""; }); }); }
  function saveSettings(event) { event.preventDefault(); var provider = val("settings-provider"), config = {}; ["model", "timeout_s", "base_url"].forEach(function (key) { var input = $("settings-" + key); if (input && input.value) config[key] = key === "timeout_s" ? Number(input.value) : input.value; }); var key = $("settings-api-key") ? val("settings-api-key") : ""; if (key && provider === "openai_compatible") config.api_key = key; var providers = state.settings && state.settings.providers || {}; providers[provider] = Object.assign({}, providers[provider] || {}, config); api("PUT", "/settings", { provider: provider, retain_photos: $("settings-retain-photos").checked, providers: providers }).then(function (data) { state.settings = data; txt($("settings-status"), "已保存"); if ($("settings-api-key")) $("settings-api-key").value = ""; }).catch(function (error) { txt($("settings-error"), error.message); }); }
  $("today-label").textContent = state.date; $("entry-form").addEventListener("submit", submitEntry); $("entry-type").addEventListener("change", toggleFields); $("profile-form").addEventListener("submit", submitProfile); $("preferences-form").addEventListener("submit", submitPreferences); $("estimate-form").addEventListener("submit", submitEstimate); $("estimate-add").addEventListener("click", addEstimateItem); $("estimate-save").addEventListener("click", saveEstimate); $("settings-form").addEventListener("submit", saveSettings); $("settings-provider").addEventListener("change", providerFields); $("plan-button").addEventListener("click", makePlan); $("refresh-button").addEventListener("click", loadAll); document.querySelectorAll(".period-button").forEach(function (button) { button.addEventListener("click", function () { state.period = Number(button.dataset.period); document.querySelectorAll(".period-button").forEach(function (x) { x.classList.toggle("active", x === button); }); loadArchive(); }); }); toggleFields(); providerFields(); loadSettings(); loadAll();
  var _planRender = renderPlan;
  renderPlan = function (data) { _planRender(data); var box = $("plan-result"); (data.warnings || []).forEach(function (warning) { var note = document.createElement("p"); note.className = "plan-warning"; txt(note, "提醒：" + warning); box.appendChild(note); }); (data.meals || []).forEach(function (meal, index) { if (!Array.isArray(meal.ingredients) || !box.children[index]) return; var list = document.createElement("ul"); list.className = "ingredients"; meal.ingredients.forEach(function (ingredient) { var item = document.createElement("li"); txt(item, typeof ingredient === "string" ? ingredient : (ingredient.name || ingredient.food || "食材") + (ingredient.portion ? " · " + ingredient.portion : "")); list.appendChild(item); }); box.children[index].appendChild(list); }); };
}());
